jobs:
- name: in_out
  public: true
  plan:
  - task: make-a-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: sh
        args:
          - -exc #for shell commands, -exc is necessary
          - ls -la; echo "Created a file on $(date)" > ./files/created_file # ; means period and is followed by next command to execute
      outputs:
        - name: files #it is stored as artifact folder
  - task: consume-the-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      inputs:
       - name: files # now the artifact folder files is copied into new container created for this task consume-the-file
      run:
        path: cat
        args:
          - ./files/created_file # if inputs not defined no file in stored(ls : no files) then build fails