jobs:
- name: job
  public: false
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo #echo "Hello world!"
        args: ["Hello world!"]