resources:
- name: trigger-every-30-second
  type: time
  source:
    interval: 30s

jobs:
- name: run-forrest-run
  plan:
  - get: trigger-every-30-second
    trigger: false # if set to false the triggering of pipeline for every 30s stops, play around to understand
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo #echo "Hello world!"
        args: ["Hello world!"]

- name: run-bubba-run
  plan:
  - get: trigger-every-30-second
    trigger: true # only passed after job1 shall be triggered even if trigger here is set to true
    passed:
      - run-forrest-run
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo #echo "Hello world!"
        args: ["Hello world! this is the second task"]